// Exercise to muscle group mapping (ported from Python)

import { MuscleGroup } from './types';

interface ExerciseMapping {
  muscle: MuscleGroup;
  secondary: MuscleGroup[];
}

export const EXERCISE_MUSCLE_MAP: Record<string, ExerciseMapping> = {
  // Quadriceps
  'Barbell Back Squat': { muscle: 'Quadriceps', secondary: ['Hamstrings', 'Glutes'] },
  'Barbell Front Squat': { muscle: 'Quadriceps', secondary: [] },
  'Bulgarian Split Squat': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Leg Press': { muscle: 'Quadriceps', secondary: [] },
  'Leg Extension': { muscle: 'Quadriceps', secondary: [] },
  'Hack Squat': { muscle: 'Quadriceps', secondary: [] },

  // Hamstrings
  'Romanian Deadlift': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },
  'Barbell Deadlift': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },
  'Sumo Deadlift': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },
  'Leg Curl': { muscle: 'Hamstrings', secondary: [] },
  'Nordic Hamstring Curl': { muscle: 'Hamstrings', secondary: [] },
  'Seated Back Extension': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },

  // Calves
  'Standing Calf Raise': { muscle: 'Calves', secondary: [] },
  'Seated Calf Raise': { muscle: 'Calves', secondary: [] },
  'Seated Machine Calf Press': { muscle: 'Calves', secondary: [] },
  'Calf Press': { muscle: 'Calves', secondary: [] },

  // Glutes
  'Machine Hip Adductor': { muscle: 'Glutes', secondary: [] },
  'Machine Hip Abductor': { muscle: 'Glutes', secondary: [] },
  'Glute Kickback Machine': { muscle: 'Glutes', secondary: [] },

  // Chest
  'Barbell Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Barbell Incline Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Dumbbell Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Dumbbell Incline Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Incline Dumbbell Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Dumbbell Incline Fly': { muscle: 'Chest', secondary: ['Shoulders'] },
  'Cable Chest Fly': { muscle: 'Chest', secondary: ['Shoulders'] },
  'Pec Deck Machine': { muscle: 'Chest', secondary: [] },

  // Back
  'Bent Over Barbell Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Pendlay Row': { muscle: 'Back', secondary: ['Biceps'] },
  'T-Bar Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Seated Cable Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Lat Pulldown': { muscle: 'Back', secondary: ['Biceps'] },
  'Barbell Shrug': { muscle: 'Back', secondary: [] },
  'Face Pull': { muscle: 'Back', secondary: ['Shoulders'] },

  // Shoulders
  'Barbell Shoulder Press': { muscle: 'Shoulders', secondary: ['Triceps'] },
  'Dumbbell Lateral Raise': { muscle: 'Shoulders', secondary: [] },
  'Cable Lateral Raise': { muscle: 'Shoulders', secondary: [] },

  // Biceps
  'Barbell Curl': { muscle: 'Biceps', secondary: [] },
  'Barbell Bicep Drag Curl': { muscle: 'Biceps', secondary: [] },
  'Incline Dumbbell Curl': { muscle: 'Biceps', secondary: [] },
  'Hammer Curl': { muscle: 'Biceps', secondary: [] },
  'Preacher Curl': { muscle: 'Biceps', secondary: [] },

  // Triceps
  'Cable Rope Overhead Triceps Extension': { muscle: 'Triceps', secondary: [] },
  'Overhead Triceps Extension': { muscle: 'Triceps', secondary: [] },
  'Cable Triceps Pushdown': { muscle: 'Triceps', secondary: [] },
  'Close-Grip Bench Press': { muscle: 'Triceps', secondary: ['Chest'] },
  'Dip': { muscle: 'Triceps', secondary: ['Chest'] },
  'Cable Rope Tricep Extension': { muscle: 'Triceps', secondary: [] },
  'Dumbbell Tricep Extension': { muscle: 'Triceps', secondary: [] },
  'EZ-Bar Overhead Tricep Extension': { muscle: 'Triceps', secondary: [] },
  'Dumbbell Skullcrusher': { muscle: 'Triceps', secondary: [] },
  'Skullcrusher': { muscle: 'Triceps', secondary: [] },
  'Single Arm Dumbbell Tricep Extension': { muscle: 'Triceps', secondary: [] },
  'Cable Underhand Tricep Pushdown': { muscle: 'Triceps', secondary: [] },
  'Machine Tricep Extension': { muscle: 'Triceps', secondary: [] },
  'Machine Tricep Dip': { muscle: 'Triceps', secondary: [] },
  'Dumbbell Kickbacks': { muscle: 'Triceps', secondary: [] },
  'Lateral Cable Tricep Extension': { muscle: 'Triceps', secondary: [] },

  // Additional exercises from user CSV
  'Deadlift': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },
  'Trap Bar Deadlift': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },
  'Back Squat': { muscle: 'Quadriceps', secondary: ['Hamstrings', 'Glutes'] },
  'Front Squat': { muscle: 'Quadriceps', secondary: [] },
  'Split Squat': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Lunge': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Reverse Lunge': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Walking Lunge': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Barbell Lunge': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Dumbbell Lunge': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Step Up': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Dumbbell Step Up': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Barbell Step Up': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Lateral Step Up': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Machine Leg Press': { muscle: 'Quadriceps', secondary: [] },
  'Dumbbell Squat': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Smith Machine Squat': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Sumo Squat': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Goblet Squat': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Kettlebell Goblet Squat': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Box Squat': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Pause Back Squat': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Single Leg Leg Extension': { muscle: 'Quadriceps', secondary: [] },
  'Dumbbell Bulgarian Split Squat': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Smith Machine Single-Leg Split Squat': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Pulse Lunge': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Curtsy Lunge': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Dumbbell Curtsy Lunge': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Lunge Jump': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Lateral Step Up with Knee Drive': { muscle: 'Quadriceps', secondary: ['Glutes'] },
  'Side Lunge': { muscle: 'Quadriceps', secondary: ['Glutes'] },

  'Dumbbell Romanian Deadlift': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },
  'Good Morning': { muscle: 'Hamstrings', secondary: ['Back'] },
  'Stiff-Legged Barbell Good Morning': { muscle: 'Hamstrings', secondary: ['Back'] },
  'Dumbbell Stiff Legged Deadlift': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },
  'Seated Leg Curl': { muscle: 'Hamstrings', secondary: [] },
  'Lying Hamstrings Curl': { muscle: 'Hamstrings', secondary: [] },
  'Back Extensions': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },
  'Incline Back Extension': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },
  'Reverse Hyperextension': { muscle: 'Hamstrings', secondary: ['Glutes'] },
  'Single Leg Romanian Deadlift': { muscle: 'Hamstrings', secondary: ['Glutes'] },
  'Single Leg Kettlebell Deadlift': { muscle: 'Hamstrings', secondary: ['Glutes'] },
  'Snatch Deadlift': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },
  'Clean Deadlift': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },
  'Smith Machine Stiff-Legged Deadlift': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },
  'Rack Pulls': { muscle: 'Hamstrings', secondary: ['Back'] },
  'Kettlebell Swing': { muscle: 'Hamstrings', secondary: ['Glutes', 'Back'] },
  'Single Arm Kettlebell Swing': { muscle: 'Hamstrings', secondary: ['Glutes', 'Back'] },
  'Alternating Single Arm Kettlebell Swing': { muscle: 'Hamstrings', secondary: ['Glutes', 'Back'] },
  'Cable Pull Through': { muscle: 'Hamstrings', secondary: ['Glutes'] },
  'Deadlift to Calf Raise': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes', 'Calves'] },
  'Dumbbell Romanian Deadlift to Shrug': { muscle: 'Hamstrings', secondary: ['Back', 'Glutes'] },

  'Smith Machine Calf Raise': { muscle: 'Calves', secondary: [] },
  'Standing Machine Calf Press': { muscle: 'Calves', secondary: [] },

  'Hip Thrust': { muscle: 'Glutes', secondary: ['Hamstrings'] },
  'Single Leg Glute Bridge': { muscle: 'Glutes', secondary: ['Hamstrings'] },
  'Single Leg Kickback': { muscle: 'Glutes', secondary: [] },
  'Cable Hip Extension': { muscle: 'Glutes', secondary: [] },
  'Straight Leg Kickback': { muscle: 'Glutes', secondary: [] },
  'Frog Pump': { muscle: 'Glutes', secondary: [] },

  'Chest Dip': { muscle: 'Chest', secondary: ['Triceps'] },
  'Push Up': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Decline Push Up': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Incline Push Up': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Diamond Push Up': { muscle: 'Chest', secondary: ['Triceps'] },
  'Pike Push Up': { muscle: 'Chest', secondary: ['Shoulders', 'Triceps'] },
  'Hand Release Push Up': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Tricep Push Up': { muscle: 'Chest', secondary: ['Triceps'] },
  'Incline Tricep Push Up': { muscle: 'Chest', secondary: ['Triceps'] },
  'Push Up on Knees': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Rotation Push Up': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Downward Dog Push Up': { muscle: 'Chest', secondary: ['Shoulders', 'Triceps'] },
  'Single Arm Push Up': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Walkout to Push Up': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Plank Surrender': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Machine Fly': { muscle: 'Chest', secondary: [] },
  'Dumbbell Fly': { muscle: 'Chest', secondary: ['Shoulders'] },
  'Cable Crossover Fly': { muscle: 'Chest', secondary: ['Shoulders'] },
  'Low Cable Chest Fly': { muscle: 'Chest', secondary: ['Shoulders'] },
  'Single Arm Low Cable Crossover Fly': { muscle: 'Chest', secondary: ['Shoulders'] },
  'Mid Cable Crossover Fly': { muscle: 'Chest', secondary: ['Shoulders'] },
  'Single Arm Cable Crossover': { muscle: 'Chest', secondary: ['Shoulders'] },
  'Dumbbell Floor Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Floor Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Machine Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Pause Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Pause Barbell Incline Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Smith Machine Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Smith Machine Incline Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Smith Machine Close-Grip Bench Press': { muscle: 'Chest', secondary: ['Triceps'] },
  'Reverse Grip Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Alternating Dumbbell Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Dumbbell Decline Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Barbell Decline Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Pause Barbell Decline Bench Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Smith Machine Decline Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Dumbbell Decline Fly': { muscle: 'Chest', secondary: ['Shoulders'] },
  'Cable Chest Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Incline Cable Chest Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Single Arm Cable Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Dumbbell Squeeze Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Incline Dumbbell Squeeze Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Svend Press': { muscle: 'Chest', secondary: ['Shoulders'] },
  'Hammerstrength Chest Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },
  'Hammerstrength Incline Chest Press': { muscle: 'Chest', secondary: ['Triceps', 'Shoulders'] },

  'Pull Up': { muscle: 'Back', secondary: ['Biceps'] },
  'Chin Up': { muscle: 'Back', secondary: ['Biceps'] },
  'Australian Chin Up': { muscle: 'Back', secondary: ['Biceps'] },
  'Wide Grip Pull Up': { muscle: 'Back', secondary: ['Biceps'] },
  'Neutral Grip Pull Up': { muscle: 'Back', secondary: ['Biceps'] },
  'Mixed Grip Pull Up': { muscle: 'Back', secondary: ['Biceps'] },
  'V-Bar Pull Up': { muscle: 'Back', secondary: ['Biceps'] },
  'Assisted Wide Grip Pull Up': { muscle: 'Back', secondary: ['Biceps'] },
  'Assisted Dip': { muscle: 'Back', secondary: ['Biceps'] },
  'Scapular Pull Up': { muscle: 'Back', secondary: [] },
  'Wide Grip Lat Pulldown': { muscle: 'Back', secondary: ['Biceps'] },
  'V-Bar Pulldown': { muscle: 'Back', secondary: ['Biceps'] },
  'Reverse Grip Pull Down': { muscle: 'Back', secondary: ['Biceps'] },
  'Cable Crossover Lat Pulldown': { muscle: 'Back', secondary: ['Biceps'] },
  'Single Arm Lat Pulldown': { muscle: 'Back', secondary: ['Biceps'] },
  'Straight-Arm Pulldown': { muscle: 'Back', secondary: [] },
  'Cable Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Cable Row with Squat': { muscle: 'Back', secondary: ['Biceps', 'Quadriceps'] },
  'Dumbbell Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Dumbbell Bent Over Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Incline Dumbbell Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Reverse Grip Barbell Bent Over Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Smith Machine Bent Over Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Trap Bar Bent Over Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Machine Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Kettlebell Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Kettlebell Alternating Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Shotgun Row': { muscle: 'Back', secondary: ['Biceps'] },
  '1/2 Kneeling Shotgun Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Renegade Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Dumbbell Back Fly': { muscle: 'Back', secondary: [] },
  'Cable Rear Delt Fly': { muscle: 'Back', secondary: ['Shoulders'] },
  'Machine Rear Delt Fly': { muscle: 'Back', secondary: ['Shoulders'] },
  'EZ-Bar Pull Over': { muscle: 'Back', secondary: [] },
  'Dumbbell Pullover': { muscle: 'Back', secondary: [] },
  'Cable Face Pull': { muscle: 'Back', secondary: ['Shoulders'] },
  'Dumbbell Shrug': { muscle: 'Back', secondary: [] },
  'Cable Shrugs': { muscle: 'Back', secondary: [] },
  'Smith Machine Shrug': { muscle: 'Back', secondary: [] },
  'Smith Machine One-Arm Upright Row': { muscle: 'Back', secondary: ['Shoulders'] },
  'Hammerstrength High Row': { muscle: 'Back', secondary: ['Biceps'] },
  'Bird Dog Rows': { muscle: 'Back', secondary: ['Biceps'] },

  'Dumbbell Shoulder Press': { muscle: 'Shoulders', secondary: ['Triceps'] },
  'Standing Dumbbell Shoulder Press': { muscle: 'Shoulders', secondary: ['Triceps'] },
  'Seated Barbell Shoulder Press': { muscle: 'Shoulders', secondary: ['Triceps'] },
  'Machine Shoulder Press': { muscle: 'Shoulders', secondary: ['Triceps'] },
  'Smith Machine Overhead Shoulder Press': { muscle: 'Shoulders', secondary: ['Triceps'] },
  'Freemotion Shoulder Press': { muscle: 'Shoulders', secondary: ['Triceps'] },
  'Cable Shoulder Press': { muscle: 'Shoulders', secondary: ['Triceps'] },
  'Hammerstrength Shoulder Press': { muscle: 'Shoulders', secondary: ['Triceps'] },
  'Arnold Dumbbell Press': { muscle: 'Shoulders', secondary: ['Triceps'] },
  'Push Press': { muscle: 'Shoulders', secondary: ['Triceps', 'Quadriceps'] },
  'Kettlebell Overhead Press': { muscle: 'Shoulders', secondary: ['Triceps'] },
  'Machine Lateral Raise': { muscle: 'Shoulders', secondary: [] },
  'Dumbbell Rear Delt Raise': { muscle: 'Shoulders', secondary: [] },
  'Dumbbell Front Raise': { muscle: 'Shoulders', secondary: [] },
  'Front Plate Raise': { muscle: 'Shoulders', secondary: [] },
  'Cable Front Raise': { muscle: 'Shoulders', secondary: [] },
  'Handle Band Forward Raise': { muscle: 'Shoulders', secondary: [] },
  'Side Laterals to Front Raise': { muscle: 'Shoulders', secondary: [] },
  'Around the Worlds': { muscle: 'Shoulders', secondary: [] },
  'Behind the Back Cable Lateral Raise': { muscle: 'Shoulders', secondary: [] },
  'Upright Row': { muscle: 'Shoulders', secondary: [] },
  'Cable Upright Row': { muscle: 'Shoulders', secondary: [] },
  'Dumbbell Upright Row': { muscle: 'Shoulders', secondary: [] },
  'Kettlebell Upright Row': { muscle: 'Shoulders', secondary: [] },
  'Dumbbell Seated Hammer Curl To Front Press': { muscle: 'Shoulders', secondary: ['Biceps'] },
  'Dumbbell Standing Hammer Curl To Front Press': { muscle: 'Shoulders', secondary: ['Biceps'] },
  'Dumbbell Squat To Shoulder Press': { muscle: 'Shoulders', secondary: ['Triceps', 'Quadriceps'] },
  'Biceps Curl To Shoulder Press': { muscle: 'Shoulders', secondary: ['Biceps', 'Triceps'] },

  'Dumbbell Bicep Curl': { muscle: 'Biceps', secondary: [] },
  'Hammer Curls': { muscle: 'Biceps', secondary: [] },
  'Incline Hammer Curl': { muscle: 'Biceps', secondary: [] },
  'Cross Body Hammer Curls': { muscle: 'Biceps', secondary: [] },
  'Seated Dumbbell Curl': { muscle: 'Biceps', secondary: [] },
  'Behind the Back Cable Bicep Curl': { muscle: 'Biceps', secondary: [] },
  'Cable Bicep Curl': { muscle: 'Biceps', secondary: [] },
  'Cable Double Bicep Curl': { muscle: 'Biceps', secondary: [] },
  'Single Arm Cable Bicep Curl': { muscle: 'Biceps', secondary: [] },
  'Overhead Cable Bicep Curl': { muscle: 'Biceps', secondary: [] },
  'Machine Preacher Curl': { muscle: 'Biceps', secondary: [] },
  'Single Arm Preacher Curl': { muscle: 'Biceps', secondary: [] },
  'Dumbbell Preacher Curls': { muscle: 'Biceps', secondary: [] },
  'Cable Preacher Curl': { muscle: 'Biceps', secondary: [] },
  'EZ-Bar Curl': { muscle: 'Biceps', secondary: [] },
  'Close-Grip EZ-Bar Curl': { muscle: 'Biceps', secondary: [] },
  'Incline EZ-Bar Curl': { muscle: 'Biceps', secondary: [] },
  'Wide Grip Barbell Curl': { muscle: 'Biceps', secondary: [] },
  'Barbell Pause Curl': { muscle: 'Biceps', secondary: [] },
  'Reverse Dumbbell Curl': { muscle: 'Biceps', secondary: [] },
  'Reverse Barbell Curl': { muscle: 'Biceps', secondary: [] },
  'Dumbbell Drag Curl': { muscle: 'Biceps', secondary: [] },
  'Dumbbell Drag Pause Curl': { muscle: 'Biceps', secondary: [] },
  'Dumbbell Hammer Pause Curl': { muscle: 'Biceps', secondary: [] },
  'Dumbbell Pause Curl': { muscle: 'Biceps', secondary: [] },
  'Dumbbell Wide Curls': { muscle: 'Biceps', secondary: [] },
  'Dumbbell No Money Curls': { muscle: 'Biceps', secondary: [] },
  'Concentration Curl': { muscle: 'Biceps', secondary: [] },
  'Spider Curls': { muscle: 'Biceps', secondary: [] },
  'Waiter Curls': { muscle: 'Biceps', secondary: [] },
  'Zottman Curl': { muscle: 'Biceps', secondary: [] },
  'Zottman Preacher Curl': { muscle: 'Biceps', secondary: [] },
  'Machine Bicep Curl': { muscle: 'Biceps', secondary: [] },
};
